#端口
server:
  port: 8888
#数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springbootzy
    username: zy
    password: zypwd
#设置上传文件大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
#mybatis
mybatis:
  typeAliasesPackage: com.zy.*.model
  mapper-locations: classpath:mapper/*.xml

#mapper接口生成代码时
mapper:
  mappers:
    - com.zy.utils.MyMapper
  not-empty: false
  identity: MYSQL
#page分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#日志
logging:
  file: logback-spring.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger- %msg%n"
  max-size: 10MB
  level:
    com.zy.*: debug







